<?php
/**
 * ACF Field Group for SEO Articles
 * SEO戦略記事専用フィールド
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_seo_article_fields',
    'title' => 'SEO戦略記事情報',
    'fields' => array(
        array(
            'key' => 'field_primary_keyword',
            'label' => 'プライマリキーワード',
            'name' => 'primary_keyword',
            'type' => 'text',
            'instructions' => '最優先で狙うキーワードを入力してください（例：東京 フォトスタジオ）',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '東京 フォトスタジオ',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_secondary_keywords',
            'label' => 'セカンダリキーワード',
            'name' => 'secondary_keywords',
            'type' => 'textarea',
            'instructions' => '関連キーワードを改行区切りで入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => "記念写真\n還暦祝い\n写真館\n家族写真\nポートレート",
            'maxlength' => '',
            'rows' => 5,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_content_strategy',
            'label' => 'コンテンツ戦略',
            'name' => 'content_strategy',
            'type' => 'radio',
            'instructions' => 'この記事の戦略タイプを選択してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'comparison' => '比較記事（○○ vs △△）',
                'guide' => '完全ガイド（○○の選び方）',
                'ranking' => 'ランキング（おすすめ○選）',
                'howto' => 'ハウツー（○○の方法）',
                'trend' => 'トレンド（2025年の○○）',
                'qanda' => 'Q&A（よくある質問）',
                'case_study' => '事例紹介（実際の体験談）',
            ),
            'allow_null' => 1,
            'other_choice' => 0,
            'default_value' => '',
            'layout' => 'vertical',
            'return_format' => 'value',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_target_conversion',
            'label' => '目標コンバージョン',
            'name' => 'target_conversion',
            'type' => 'checkbox',
            'instructions' => 'この記事から誘導したいアクション（複数選択可）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'studio_search' => 'スタジオ検索ページ誘導',
                'reservation' => '予約ページ誘導',
                'inquiry' => 'お問い合わせ誘導',
                'newsletter' => 'メルマガ登録誘導',
                'phone_call' => '電話問い合わせ',
                'download' => '資料ダウンロード',
                'social_share' => 'SNSシェア',
            ),
            'allow_custom' => 1,
            'default_value' => array(),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
            'save_custom' => 1,
        ),
        array(
            'key' => 'field_article_structure',
            'label' => '記事構成情報',
            'name' => 'article_structure',
            'type' => 'group',
            'instructions' => 'SEO効果を高めるための記事構成情報',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_estimated_word_count',
                    'label' => '想定文字数',
                    'name' => 'estimated_word_count',
                    'type' => 'number',
                    'instructions' => 'この記事の目標文字数',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 3000,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '文字',
                    'min' => 1000,
                    'max' => 10000,
                    'step' => 100,
                ),
                array(
                    'key' => 'field_estimated_reading_time',
                    'label' => '想定読了時間',
                    'name' => 'estimated_reading_time',
                    'type' => 'number',
                    'instructions' => 'この記事の想定読了時間（分）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '33',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 10,
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '分',
                    'min' => 1,
                    'max' => 60,
                    'step' => 1,
                ),
                array(
                    'key' => 'field_target_audience',
                    'label' => '対象読者',
                    'name' => 'target_audience',
                    'type' => 'select',
                    'instructions' => 'この記事のメインターゲット',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '34',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'seniors' => 'シニア世代（60-80代）',
                        'families' => 'ファミリー層',
                        'young_couples' => '若いカップル',
                        'middle_aged' => '中高年層',
                        'business' => '法人・事業者',
                        'general' => '一般（幅広い層）',
                    ),
                    'default_value' => 'seniors',
                    'allow_null' => 1,
                    'multiple' => 0,
                    'ui' => 0,
                    'return_format' => 'value',
                    'ajax' => 0,
                    'placeholder' => '',
                ),
            ),
        ),
        array(
            'key' => 'field_internal_links',
            'label' => '関連記事・内部リンク',
            'name' => 'internal_links',
            'type' => 'group',
            'instructions' => 'SEO効果向上のための内部リンク設定',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_related_studio_articles',
                    'label' => '関連スタジオ記事',
                    'name' => 'related_studio_articles',
                    'type' => 'post_object',
                    'instructions' => 'この記事に関連するスタジオ紹介記事',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'studio_features',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 1,
                    'multiple' => 1,
                    'return_format' => 'object',
                    'ui' => 1,
                ),
                array(
                    'key' => 'field_related_seo_articles',
                    'label' => '関連SEO記事',
                    'name' => 'related_seo_articles',
                    'type' => 'post_object',
                    'instructions' => 'この記事に関連する他のSEO戦略記事',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'post_type' => array(
                        0 => 'seo_articles',
                    ),
                    'taxonomy' => '',
                    'allow_null' => 1,
                    'multiple' => 1,
                    'return_format' => 'object',
                    'ui' => 1,
                ),
            ),
        ),
        array(
            'key' => 'field_seo_notes',
            'label' => 'SEO メモ・注意事項',
            'name' => 'seo_notes',
            'type' => 'textarea',
            'instructions' => 'この記事のSEO戦略に関するメモや注意事項を記載',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '競合分析結果、キーワード選定の理由、更新予定など',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'wpautop',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'seo_articles',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'SEO戦略記事で使用するカスタムフィールドです。キーワード戦略と内部リンク設計を効率化します。',
));

endif;