<?php
/**
 * ACF Field Group for Studio Feature Articles
 * スタジオ紹介記事専用フィールド
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_studio_feature_fields',
    'title' => 'スタジオ紹介記事情報',
    'fields' => array(
        array(
            'key' => 'field_target_studio',
            'label' => '対象スタジオ',
            'name' => 'target_studio',
            'type' => 'post_object',
            'instructions' => '紹介するスタジオを選択してください（既存のstudio_shops データベースと連携）',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'post_type' => array(),  // 全ての投稿タイプから選択可能（後でstudio投稿タイプ作成時に制限）
            'taxonomy' => '',
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
        ),
        array(
            'key' => 'field_feature_highlights',
            'label' => 'アピールポイント',
            'name' => 'feature_highlights',
            'type' => 'checkbox',
            'instructions' => 'このスタジオの特徴・魅力を選択してください（複数選択可）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'station_access' => '駅近アクセス抜群',
                'parking' => '無料駐車場完備',
                'barrier_free' => 'バリアフリー対応',
                'kids_space' => 'キッズスペースあり',
                'costume_rich' => '衣装レンタル豊富',
                'data_service' => 'データ納品サービス',
                'price_reasonable' => 'リーズナブル料金',
                'staff_professional' => '経験豊富スタッフ',
                'weekend_available' => '土日祝日営業',
                'early_morning' => '早朝撮影対応',
                'same_day_delivery' => '当日納品可能',
            ),
            'allow_custom' => 1,
            'default_value' => array(),
            'layout' => 'vertical',
            'toggle' => 0,
            'return_format' => 'value',
            'save_custom' => 1,
        ),
        array(
            'key' => 'field_promotion_campaign',
            'label' => 'キャンペーン情報',
            'name' => 'promotion_campaign',
            'type' => 'group',
            'instructions' => '現在実施中のキャンペーンがあれば入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_campaign_title',
                    'label' => 'キャンペーン名',
                    'name' => 'campaign_title',
                    'type' => 'text',
                    'instructions' => 'キャンペーンのタイトルを入力',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '例：新春特別割引キャンペーン',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_discount_rate',
                    'label' => '割引率',
                    'name' => 'discount_rate',
                    'type' => 'number',
                    'instructions' => '割引率を数値で入力（%は自動で付きます）',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '20',
                    'prepend' => '',
                    'append' => '%',
                    'min' => 0,
                    'max' => 100,
                    'step' => 1,
                ),
                array(
                    'key' => 'field_campaign_period_start',
                    'label' => 'キャンペーン開始日',
                    'name' => 'campaign_period_start',
                    'type' => 'date_picker',
                    'instructions' => 'キャンペーン開始日',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y年m月d日',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'field_campaign_period_end',
                    'label' => 'キャンペーン終了日',
                    'name' => 'campaign_period_end',
                    'type' => 'date_picker',
                    'instructions' => 'キャンペーン終了日',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'Y年m月d日',
                    'return_format' => 'Y-m-d',
                    'first_day' => 1,
                ),
                array(
                    'key' => 'field_campaign_description',
                    'label' => 'キャンペーン詳細',
                    'name' => 'campaign_description',
                    'type' => 'textarea',
                    'instructions' => 'キャンペーンの詳細説明',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => 'キャンペーンの詳細、利用条件などを入力してください',
                    'maxlength' => '',
                    'rows' => 3,
                    'new_lines' => 'wpautop',
                ),
            ),
        ),
        array(
            'key' => 'field_studio_contact_info',
            'label' => 'スタジオ連絡先情報',
            'name' => 'studio_contact_info',
            'type' => 'group',
            'instructions' => '記事で紹介するスタジオの連絡先情報（自動で取得されますが、手動で上書き可能）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'layout' => 'block',
            'sub_fields' => array(
                array(
                    'key' => 'field_studio_phone',
                    'label' => '電話番号',
                    'name' => 'studio_phone',
                    'type' => 'text',
                    'instructions' => 'スタジオの電話番号',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '03-1234-5678',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_studio_address',
                    'label' => '住所',
                    'name' => 'studio_address',
                    'type' => 'text',
                    'instructions' => 'スタジオの住所',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '東京都新宿区...',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_business_hours',
                    'label' => '営業時間',
                    'name' => 'business_hours',
                    'type' => 'text',
                    'instructions' => 'スタジオの営業時間',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '9:00-18:00',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
                array(
                    'key' => 'field_studio_holidays',
                    'label' => '定休日',
                    'name' => 'studio_holidays',
                    'type' => 'text',
                    'instructions' => 'スタジオの定休日',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'placeholder' => '水曜日',
                    'prepend' => '',
                    'append' => '',
                    'maxlength' => '',
                ),
            ),
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'studio_features',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => 'スタジオ紹介記事で使用するカスタムフィールドです。対象スタジオを選択すると、自動で基本情報が取得されます。',
));

endif;