<?php
/**
 * ACF Field Groups for Studio Shops
 * 
 * @package 678studio
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_studio_shops',
    'title' => 'スタジオ店舗情報',
    'fields' => array(
        // 基本情報タブ
        array(
            'key' => 'field_studio_tab_basic',
            'label' => '基本情報',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_shop_id',
            'label' => '店舗ID',
            'name' => 'shop_id',
            'type' => 'number',
            'instructions' => '既存システムとの互換性のための店舗ID（自動生成されます）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
            'readonly' => 1,
        ),
        array(
            'key' => 'field_studio_store_name_base',
            'label' => '基本店舗名',
            'name' => 'store_name_base',
            'type' => 'text',
            'instructions' => '例: スタジオアリス、写真の○○など（基本となる店舗ブランド名）',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => 'スタジオアリス',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_branch_name',
            'label' => '支店名',
            'name' => 'branch_name',
            'type' => 'text',
            'instructions' => '例: 新宿東口店、渋谷本店など（支店・店舗名）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '新宿東口店',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_store_name',
            'label' => '店舗名（旧フィールド）',
            'name' => 'store_name',
            'type' => 'textarea',
            'instructions' => '既存データとの互換性用（新しい基本店舗名+支店名を使用してください）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
            ),
            'default_value' => '',
            'placeholder' => '例：678スタジオ渋谷店',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_studio_address',
            'label' => '住所',
            'name' => 'address',
            'type' => 'textarea',
            'instructions' => '店舗の住所を入力してください',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '例: 東京都渋谷区〇〇1-2-3 〇〇ビル4F',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_studio_phone',
            'label' => '電話番号',
            'name' => 'phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 03-1234-5678',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_nearest_station',
            'label' => '最寄り駅',
            'name' => 'nearest_station',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: JR渋谷駅',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_access_details',
            'label' => 'アクセス詳細',
            'name' => 'access_details',
            'type' => 'textarea',
            'instructions' => '店舗へのアクセス方法や目印など詳細情報を入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
            ),
            'default_value' => '',
            'placeholder' => '例：JR渋谷駅東口から徒歩5分。ハチ公像を背に道玄坂方面へ向かい、最初の交差点を右折。',
            'maxlength' => '',
            'rows' => 3,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_studio_business_hours',
            'label' => '営業時間',
            'name' => 'business_hours',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 10:00-19:00',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_holidays',
            'label' => '定休日',
            'name' => 'holidays',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 水曜日',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_email',
            'label' => 'メールアドレス',
            'name' => 'company_email',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => 'example@studio.com',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_studio_website_url_new',
            'label' => 'ウェブサイトURL',
            'name' => 'website_url',
            'type' => 'text',
            'instructions' => '店舗の公式ウェブサイトURLを入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => 'https://example.com',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_studio_prefecture',
            'label' => '都道府県',
            'name' => 'prefecture',
            'type' => 'select',
            'instructions' => '店舗所在地の都道府県を選択してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'choices' => array(
                '北海道' => '北海道',
                '青森県' => '青森県',
                '岩手県' => '岩手県',
                '宮城県' => '宮城県',
                '秋田県' => '秋田県',
                '山形県' => '山形県',
                '福島県' => '福島県',
                '茨城県' => '茨城県',
                '栃木県' => '栃木県',
                '群馬県' => '群馬県',
                '埼玉県' => '埼玉県',
                '千葉県' => '千葉県',
                '東京都' => '東京都',
                '神奈川県' => '神奈川県',
                '新潟県' => '新潟県',
                '富山県' => '富山県',
                '石川県' => '石川県',
                '福井県' => '福井県',
                '山梨県' => '山梨県',
                '長野県' => '長野県',
                '岐阜県' => '岐阜県',
                '静岡県' => '静岡県',
                '愛知県' => '愛知県',
                '三重県' => '三重県',
                '滋賀県' => '滋賀県',
                '京都府' => '京都府',
                '大阪府' => '大阪府',
                '兵庫県' => '兵庫県',
                '奈良県' => '奈良県',
                '和歌山県' => '和歌山県',
                '鳥取県' => '鳥取県',
                '島根県' => '島根県',
                '岡山県' => '岡山県',
                '広島県' => '広島県',
                '山口県' => '山口県',
                '徳島県' => '徳島県',
                '香川県' => '香川県',
                '愛媛県' => '愛媛県',
                '高知県' => '高知県',
                '福岡県' => '福岡県',
                '佐賀県' => '佐賀県',
                '長崎県' => '長崎県',
                '熊本県' => '熊本県',
                '大分県' => '大分県',
                '宮崎県' => '宮崎県',
                '鹿児島県' => '鹿児島県',
                '沖縄県' => '沖縄県',
            ),
            'default_value' => '',
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '都道府県を選択してください',
        ),
        
        // 認定店設定
        array(
            'key' => 'field_studio_certified_store',
            'label' => '認定店',
            'name' => 'is_certified_store',
            'type' => 'true_false',
            'instructions' => 'チェックすると認定店として扱われ、追加機能が利用できます',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'message' => '認定店として設定する',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '認定店',
            'ui_off_text' => '一般店',
        ),
        
        // 店舗紹介（基本情報タブに配置）
        array(
            'key' => 'field_studio_introduction',
            'label' => '店舗紹介',
            'name' => 'store_introduction',
            'type' => 'textarea',
            'instructions' => '店舗の詳細な紹介文を入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '店舗の特徴や強み、サービス内容について詳しく記述してください',
            'maxlength' => '',
            'rows' => 6,
            'new_lines' => 'br',
        ),
        
        // 撮影プランタブ
        array(
            'key' => 'field_studio_tab_plans',
            'label' => '撮影プラン',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
            'conditional_logic' => 0,
        ),
        // 撮影プラン1
        array(
            'key' => 'field_studio_plan1_title',
            'label' => '撮影プラン1 - タイトル',
            'name' => 'plan1_name',
            'type' => 'text',
            'instructions' => '1つ目の撮影プランのタイトル',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '60',
            ),
            'default_value' => '',
            'placeholder' => '例: ベーシックプラン',
        ),
        array(
            'key' => 'field_studio_plan1_price',
            'label' => '撮影プラン1 - 料金',
            'name' => 'plan1_price',
            'type' => 'number',
            'instructions' => '料金を数字のみで入力（¥マークは自動で付加されます）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '10000',
            'prepend' => '¥',
            'append' => '円',
            'min' => 0,
            'max' => '',
            'step' => 1000,
        ),
        array(
            'key' => 'field_studio_plan1_duration',
            'label' => '撮影プラン1 - 目安時間',
            'name' => 'plan1_duration',
            'type' => 'number',
            'instructions' => '撮影の目安時間を分単位で入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '30',
            'append' => '分',
            'min' => 5,
            'max' => 300,
            'step' => 5,
        ),
        array(
            'key' => 'field_studio_plan1_description',
            'label' => '撮影プラン1 - 詳細',
            'name' => 'plan1_description',
            'type' => 'textarea',
            'instructions' => 'プランの内容や特徴を詳しく記述してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => 'プランに含まれる内容、撮影時間、カット数など',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_studio_plan1_image',
            'label' => '撮影プラン1 - 画像',
            'name' => 'plan1_image',
            'type' => 'image',
            'instructions' => 'このプランを表現する画像を選択してください（推奨サイズ: 800x600px以上）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 400,
            'min_height' => 300,
            'min_size' => '',
            'max_width' => 2000,
            'max_height' => 2000,
            'max_size' => '5 MB',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        
        // 撮影プラン2
        array(
            'key' => 'field_studio_plan2_title',
            'label' => '撮影プラン2 - タイトル',
            'name' => 'plan2_name',
            'type' => 'text',
            'instructions' => '2つ目の撮影プランのタイトル（任意）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '60',
            ),
            'default_value' => '',
            'placeholder' => '例: スタンダードプラン',
        ),
        array(
            'key' => 'field_studio_plan2_price',
            'label' => '撮影プラン2 - 料金',
            'name' => 'plan2_price',
            'type' => 'number',
            'instructions' => '料金を数字のみで入力（¥マークは自動で付加されます）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '20000',
            'prepend' => '¥',
            'append' => '円',
            'min' => 0,
            'max' => '',
            'step' => 1000,
        ),
        array(
            'key' => 'field_studio_plan2_duration',
            'label' => '撮影プラン2 - 目安時間',
            'name' => 'plan2_duration',
            'type' => 'number',
            'instructions' => '撮影の目安時間を分単位で入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '60',
            'append' => '分',
            'min' => 5,
            'max' => 300,
            'step' => 5,
        ),
        array(
            'key' => 'field_studio_plan2_description',
            'label' => '撮影プラン2 - 詳細',
            'name' => 'plan2_description',
            'type' => 'textarea',
            'instructions' => 'プランの内容や特徴を詳しく記述してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => 'プランに含まれる内容、撮影時間、カット数など',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_studio_plan2_image',
            'label' => '撮影プラン2 - 画像',
            'name' => 'plan2_image',
            'type' => 'image',
            'instructions' => 'このプランを表現する画像を選択してください（推奨サイズ: 800x600px以上）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 400,
            'min_height' => 300,
            'min_size' => '',
            'max_width' => 2000,
            'max_height' => 2000,
            'max_size' => '5 MB',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        
        // 撮影プラン3
        array(
            'key' => 'field_studio_plan3_title',
            'label' => '撮影プラン3 - タイトル',
            'name' => 'plan3_name',
            'type' => 'text',
            'instructions' => '3つ目の撮影プランのタイトル（任意）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '60',
            ),
            'default_value' => '',
            'placeholder' => '例: プレミアムプラン',
        ),
        array(
            'key' => 'field_studio_plan3_price',
            'label' => '撮影プラン3 - 料金',
            'name' => 'plan3_price',
            'type' => 'number',
            'instructions' => '料金を数字のみで入力（¥マークは自動で付加されます）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '30000',
            'prepend' => '¥',
            'append' => '円',
            'min' => 0,
            'max' => '',
            'step' => 1000,
        ),
        array(
            'key' => 'field_studio_plan3_duration',
            'label' => '撮影プラン3 - 目安時間',
            'name' => 'plan3_duration',
            'type' => 'number',
            'instructions' => '撮影の目安時間を分単位で入力してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
            ),
            'default_value' => '',
            'placeholder' => '90',
            'append' => '分',
            'min' => 5,
            'max' => 300,
            'step' => 5,
        ),
        array(
            'key' => 'field_studio_plan3_description',
            'label' => '撮影プラン3 - 詳細',
            'name' => 'plan3_description',
            'type' => 'textarea',
            'instructions' => 'プランの内容や特徴を詳しく記述してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => 'プランに含まれる内容、撮影時間、カット数など',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_studio_plan3_image',
            'label' => '撮影プラン3 - 画像',
            'name' => 'plan3_image',
            'type' => 'image',
            'instructions' => 'このプランを表現する画像を選択してください（推奨サイズ: 800x600px以上）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 400,
            'min_height' => 300,
            'min_size' => '',
            'max_width' => 2000,
            'max_height' => 2000,
            'max_size' => '5 MB',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        
        // 地図タブ
        array(
            'key' => 'field_studio_tab_map',
            'label' => '地図',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_map_url',
            'label' => 'Google Map埋め込みコード',
            'name' => 'map_url',
            'type' => 'textarea',
            'instructions' => 'Google Mapの埋め込みコード（iframeタグ）を貼り付けてください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '<iframe src="https://www.google.com/maps/embed?..." width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => '',
        ),
        
        // メイン画像タブ
        array(
            'key' => 'field_studio_tab_gallery',
            'label' => 'メイン画像',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_main_image',
            'label' => 'メイン画像',
            'name' => 'main_image',
            'type' => 'image',
            'instructions' => '店舗一覧で表示されるメイン画像（推奨サイズ: 800x600px以上）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 400,
            'min_height' => 300,
            'min_size' => '',
            'max_width' => 2000,
            'max_height' => 2000,
            'max_size' => '5 MB',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        
        // スタッフタブ
        array(
            'key' => 'field_studio_tab_staff',
            'label' => 'スタッフ',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        // スタッフ1
        array(
            'key' => 'field_studio_staff1_name',
            'label' => 'スタッフ1 - 名前',
            'name' => 'staff1_name',
            'type' => 'text',
            'instructions' => '1人目のスタッフ名',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 田中 太郎',
        ),
        array(
            'key' => 'field_studio_staff1_position',
            'label' => 'スタッフ1 - 役職',
            'name' => 'staff1_position',
            'type' => 'text',
            'instructions' => '役職や肩書き',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 店長',
        ),
        array(
            'key' => 'field_studio_staff1_image',
            'label' => 'スタッフ1 - 写真',
            'name' => 'staff1_image',
            'type' => 'image',
            'instructions' => 'スタッフの写真',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '30',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        array(
            'key' => 'field_studio_staff1_message',
            'label' => 'スタッフ1 - メッセージ',
            'name' => 'staff1_message',
            'type' => 'textarea',
            'instructions' => 'スタッフからのメッセージ',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '70',
            ),
            'default_value' => '',
            'placeholder' => 'お客様へのメッセージや自己紹介など',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        
        // スタッフ2
        array(
            'key' => 'field_studio_staff2_name',
            'label' => 'スタッフ2 - 名前',
            'name' => 'staff2_name',
            'type' => 'text',
            'instructions' => '2人目のスタッフ名（任意）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 佐藤 花子',
        ),
        array(
            'key' => 'field_studio_staff2_position',
            'label' => 'スタッフ2 - 役職',
            'name' => 'staff2_position',
            'type' => 'text',
            'instructions' => '役職や肩書き',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: アシスタント',
        ),
        array(
            'key' => 'field_studio_staff2_image',
            'label' => 'スタッフ2 - 写真',
            'name' => 'staff2_image',
            'type' => 'image',
            'instructions' => 'スタッフの写真',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '30',
            ),
            'return_format' => 'array',
            'preview_size' => 'thumbnail',
            'library' => 'all',
        ),
        array(
            'key' => 'field_studio_staff2_message',
            'label' => 'スタッフ2 - メッセージ',
            'name' => 'staff2_message',
            'type' => 'textarea',
            'instructions' => 'スタッフからのメッセージ',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '70',
            ),
            'default_value' => '',
            'placeholder' => 'お客様へのメッセージや自己紹介など',
            'rows' => 3,
            'new_lines' => 'br',
        ),
        
        // SEOタブ
        array(
            'key' => 'field_studio_tab_seo',
            'label' => 'SEO設定',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_seo_title',
            'label' => 'SEOタイトル',
            'name' => 'seo_title',
            'type' => 'text',
            'instructions' => '検索結果に表示されるタイトル（空の場合は自動生成）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 60,
        ),
        array(
            'key' => 'field_studio_seo_description',
            'label' => 'メタディスクリプション',
            'name' => 'seo_description',
            'type' => 'textarea',
            'instructions' => '検索結果に表示される説明文（空の場合は自動生成）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 160,
            'rows' => 3,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_studio_seo_keywords',
            'label' => 'キーワード',
            'name' => 'seo_keywords',
            'type' => 'text',
            'instructions' => 'カンマ区切りでキーワードを入力',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '例: 写真館,記念撮影,シニア撮影',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'studio_shops',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        'the_content',
        'excerpt',
        'discussion',
        'comments',
        'revisions',
        'slug',
        'author',
        'format',
        'page_attributes',
        'categories',
        'tags',
        'send-trackbacks',
        'featured_image',
        'taxonomies',
        'studio_prefecture',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

endif;