<?php
/**
 * ACF Field Groups for Studio Shops
 * 
 * @package 678studio
 */

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
    'key' => 'group_studio_shops',
    'title' => 'スタジオ店舗情報',
    'fields' => array(
        // 基本情報タブ
        array(
            'key' => 'field_studio_tab_basic',
            'label' => '基本情報',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_shop_id',
            'label' => '店舗ID',
            'name' => 'shop_id',
            'type' => 'number',
            'instructions' => '既存システムとの互換性のための店舗ID（自動生成されます）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'min' => '',
            'max' => '',
            'step' => '',
            'readonly' => 1,
        ),
        array(
            'key' => 'field_studio_address',
            'label' => '住所',
            'name' => 'address',
            'type' => 'textarea',
            'instructions' => '店舗の住所を入力してください',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '例: 東京都渋谷区〇〇1-2-3 〇〇ビル4F',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => 'br',
        ),
        array(
            'key' => 'field_studio_phone',
            'label' => '電話番号',
            'name' => 'phone',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 03-1234-5678',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_nearest_station',
            'label' => '最寄り駅',
            'name' => 'nearest_station',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: JR渋谷駅',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_business_hours',
            'label' => '営業時間',
            'name' => 'business_hours',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 10:00-19:00',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_holidays',
            'label' => '定休日',
            'name' => 'holidays',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => '例: 水曜日',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_studio_email',
            'label' => 'メールアドレス',
            'name' => 'company_email',
            'type' => 'email',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'default_value' => '',
            'placeholder' => 'example@studio.com',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_studio_prefecture',
            'label' => '都道府県',
            'name' => 'prefecture',
            'type' => 'select',
            'instructions' => '店舗所在地の都道府県を選択してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
            ),
            'choices' => array(
                '北海道' => '北海道',
                '青森県' => '青森県',
                '岩手県' => '岩手県',
                '宮城県' => '宮城県',
                '秋田県' => '秋田県',
                '山形県' => '山形県',
                '福島県' => '福島県',
                '茨城県' => '茨城県',
                '栃木県' => '栃木県',
                '群馬県' => '群馬県',
                '埼玉県' => '埼玉県',
                '千葉県' => '千葉県',
                '東京都' => '東京都',
                '神奈川県' => '神奈川県',
                '新潟県' => '新潟県',
                '富山県' => '富山県',
                '石川県' => '石川県',
                '福井県' => '福井県',
                '山梨県' => '山梨県',
                '長野県' => '長野県',
                '岐阜県' => '岐阜県',
                '静岡県' => '静岡県',
                '愛知県' => '愛知県',
                '三重県' => '三重県',
                '滋賀県' => '滋賀県',
                '京都府' => '京都府',
                '大阪府' => '大阪府',
                '兵庫県' => '兵庫県',
                '奈良県' => '奈良県',
                '和歌山県' => '和歌山県',
                '鳥取県' => '鳥取県',
                '島根県' => '島根県',
                '岡山県' => '岡山県',
                '広島県' => '広島県',
                '山口県' => '山口県',
                '徳島県' => '徳島県',
                '香川県' => '香川県',
                '愛媛県' => '愛媛県',
                '高知県' => '高知県',
                '福岡県' => '福岡県',
                '佐賀県' => '佐賀県',
                '長崎県' => '長崎県',
                '熊本県' => '熊本県',
                '大分県' => '大分県',
                '宮崎県' => '宮崎県',
                '鹿児島県' => '鹿児島県',
                '沖縄県' => '沖縄県',
            ),
            'default_value' => '',
            'allow_null' => 1,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 0,
            'return_format' => 'value',
            'placeholder' => '都道府県を選択してください',
        ),
        
        // 地図タブ
        array(
            'key' => 'field_studio_tab_map',
            'label' => '地図',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_map_url',
            'label' => 'Google Map埋め込みコード',
            'name' => 'map_url',
            'type' => 'textarea',
            'instructions' => 'Google Mapの埋め込みコード（iframeタグ）を貼り付けてください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '<iframe src="https://www.google.com/maps/embed?..." width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>',
            'maxlength' => '',
            'rows' => 4,
            'new_lines' => '',
        ),
        
        // メイン画像タブ
        array(
            'key' => 'field_studio_tab_gallery',
            'label' => 'メイン画像',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_main_image',
            'label' => 'メイン画像',
            'name' => 'main_image',
            'type' => 'image',
            'instructions' => '店舗一覧で表示されるメイン画像（推奨サイズ: 800x600px以上）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'return_format' => 'array',
            'preview_size' => 'medium',
            'library' => 'all',
            'min_width' => 400,
            'min_height' => 300,
            'min_size' => '',
            'max_width' => 2000,
            'max_height' => 2000,
            'max_size' => '5 MB',
            'mime_types' => 'jpg,jpeg,png,webp',
        ),
        
        // スタッフタブ
        array(
            'key' => 'field_studio_tab_staff',
            'label' => 'スタッフ',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_staff',
            'label' => 'スタッフ情報',
            'name' => 'staff_members',
            'type' => 'repeater',
            'instructions' => 'スタッフの情報を追加してください',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'collapsed' => 'field_staff_name',
            'min' => 0,
            'max' => 0,
            'layout' => 'block',
            'button_label' => 'スタッフを追加',
            'sub_fields' => array(
                array(
                    'key' => 'field_staff_name',
                    'label' => 'スタッフ名',
                    'name' => 'name',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 1,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                    ),
                ),
                array(
                    'key' => 'field_staff_position',
                    'label' => '役職',
                    'name' => 'position',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                    ),
                ),
                array(
                    'key' => 'field_staff_image',
                    'label' => 'スタッフ写真',
                    'name' => 'image',
                    'type' => 'image',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '30',
                    ),
                    'return_format' => 'array',
                    'preview_size' => 'thumbnail',
                    'library' => 'all',
                ),
                array(
                    'key' => 'field_staff_message',
                    'label' => 'メッセージ',
                    'name' => 'message',
                    'type' => 'textarea',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '70',
                    ),
                    'rows' => 3,
                ),
            ),
        ),
        
        // SEOタブ
        array(
            'key' => 'field_studio_tab_seo',
            'label' => 'SEO設定',
            'name' => '',
            'type' => 'tab',
            'placement' => 'top',
            'endpoint' => 0,
        ),
        array(
            'key' => 'field_studio_seo_title',
            'label' => 'SEOタイトル',
            'name' => 'seo_title',
            'type' => 'text',
            'instructions' => '検索結果に表示されるタイトル（空の場合は自動生成）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 60,
        ),
        array(
            'key' => 'field_studio_seo_description',
            'label' => 'メタディスクリプション',
            'name' => 'seo_description',
            'type' => 'textarea',
            'instructions' => '検索結果に表示される説明文（空の場合は自動生成）',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => 160,
            'rows' => 3,
            'new_lines' => '',
        ),
        array(
            'key' => 'field_studio_seo_keywords',
            'label' => 'キーワード',
            'name' => 'seo_keywords',
            'type' => 'text',
            'instructions' => 'カンマ区切りでキーワードを入力',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
            ),
            'default_value' => '',
            'placeholder' => '例: 写真館,記念撮影,シニア撮影',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'studio_shops',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
        'the_content',
        'excerpt',
        'discussion',
        'comments',
        'revisions',
        'slug',
        'author',
        'format',
        'page_attributes',
        'categories',
        'tags',
        'send-trackbacks',
        'featured_image',
        'taxonomies',
        'studio_prefecture',
    ),
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
));

endif;