<?php
/**
 * Studio Hero Slider Section
 * Display gallery images in a slider format for studio detail page
 *
 * Phase 2: Enhanced with new studio data helpers
 */

// Get shop_id from various sources
$shop_id = 0;
if (isset($args['shop']['id'])) {
    $shop_id = $args['shop']['id'];
} elseif (isset($_GET['shop_id'])) {
    $shop_id = intval($_GET['shop_id']);
}

// Try to get data using new helper functions first
$gallery_images = $args['gallery_images'] ?? array();
$shop_name = $args['shop_name'] ?? '';

if ($shop_id > 0 && function_exists('get_studio_shop_data_simple')) {
    $shop_data = get_studio_shop_data_simple($shop_id);
    if (!isset($shop_data['error']) && !empty($shop_data['shop'])) {
        // Use data from new helper functions
        if (empty($gallery_images) && !empty($shop_data['shop']['main_gallery_images'])) {
            $gallery_images = $shop_data['shop']['main_gallery_images'];
        }
        if (empty($shop_name)) {
            $shop_name = $shop_data['shop']['name'];
        }
    }
}

// Don't render if no images
if (empty($gallery_images)) {
    return;
}
?>

<section class="studio-hero-slider" id="studio-hero-slider">
    <div class="studio-hero-slider__container">
        <div id="studio-gallery-slider" class="splide" role="group" aria-label="店舗ギャラリー - <?php echo esc_attr($shop_name); ?>">
            <div class="splide__track">
                <ul class="splide__list">
                    <?php foreach ($gallery_images as $index => $image):
                        // Handle both string URLs and array structures
                        $image_url = '';
                        if (is_string($image)) {
                            $image_url = $image;
                        } elseif (is_array($image)) {
                            // Try different possible keys
                            if (isset($image['url'])) {
                                $image_url = $image['url'];
                            } elseif (isset($image['src'])) {
                                $image_url = $image['src'];
                            } elseif (isset($image['image_url'])) {
                                $image_url = $image['image_url'];
                            } elseif (isset($image[0])) {
                                $image_url = $image[0];
                            }
                        }

                        // Skip if no valid URL found
                        if (empty($image_url)) {
                            continue;
                        }
                    ?>
                    <li class="splide__slide">
                        <img src="<?php echo esc_url($image_url); ?>"
                             alt="<?php echo esc_attr($shop_name); ?> ギャラリー画像 <?php echo $index + 1; ?>"
                             class="studio-hero-slider__image"
                             loading="<?php echo $index === 0 ? 'eager' : 'lazy'; ?>">
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <!-- Pagination will be generated by Splide.js -->

            <?php if (count($gallery_images) > 10): ?>
            <!-- Image counter for many images -->
            <div class="studio-hero-slider__counter">
                <span class="studio-hero-slider__counter-current">1</span>
                <span class="studio-hero-slider__counter-separator">/</span>
                <span class="studio-hero-slider__counter-total"><?php echo count($gallery_images); ?></span>
            </div>
            <?php endif; ?>
        </div>
    </div>
</section>