<?php
/**
 * Studio Hero Slider Section
 * Display gallery images in a slider format for studio detail page
 */

// Get data passed from parent template
$gallery_images = $args['gallery_images'] ?? array();
$shop_name = $args['shop_name'] ?? '';

// Don't render if no images
if (empty($gallery_images)) {
    return;
}
?>

<section class="studio-hero-slider" id="studio-hero-slider">
    <div class="studio-hero-slider__container">
        <div id="studio-gallery-slider" class="splide" role="group" aria-label="店舗ギャラリー - <?php echo esc_attr($shop_name); ?>">
            <div class="splide__track">
                <ul class="splide__list">
                    <?php foreach ($gallery_images as $index => $image):
                        // Handle both string URLs and array structures
                        $image_url = '';
                        if (is_string($image)) {
                            $image_url = $image;
                        } elseif (is_array($image)) {
                            // Try different possible keys
                            if (isset($image['url'])) {
                                $image_url = $image['url'];
                            } elseif (isset($image['src'])) {
                                $image_url = $image['src'];
                            } elseif (isset($image['image_url'])) {
                                $image_url = $image['image_url'];
                            } elseif (isset($image[0])) {
                                $image_url = $image[0];
                            }
                        }

                        // Skip if no valid URL found
                        if (empty($image_url)) {
                            continue;
                        }
                    ?>
                    <li class="splide__slide">
                        <img src="<?php echo esc_url($image_url); ?>"
                             alt="<?php echo esc_attr($shop_name); ?> ギャラリー画像 <?php echo $index + 1; ?>"
                             class="studio-hero-slider__image"
                             loading="<?php echo $index === 0 ? 'eager' : 'lazy'; ?>">
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <!-- Pagination will be generated by Splide.js -->
        </div>
    </div>
</section>